services:
  - type: web
    name: network-security
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MONGODB_URL_KEY
        value: mongodb+srv://garvkhullar1121_db_user:Garv123@cluster0.edswblb.mongodb.net/?appName=Cluster0

